apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-front
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels: 
        app: react-app
    spec:
      containers:
        - name: react-app
          image: krishnansai/smt-website
---
apiVersion: v1
kind: Service
metadata:
  name: book-front-src
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 8001
      targetPort: 8001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-autoscaling
  autoscaling.alpha.kubernetes.io/behavior: '{"ScaleUp":{"StabilizationWindowSeconds":0,"Policies":[{"Type":"Pods","Value":1,"PeriodSeconds":15},{"Type":"Percent","Value":10,"PeriodSeconds":15}]},"ScaleDown":{"StabilizationWindowSeconds":0,"Policies":[{"Type":"Pods","Value":1,"PeriodSeconds":15}]}}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book-front
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 4

